stages:
  - test
  - package
  - publish

default: 
  image: nixos/nix:2.24.12

variables:
  NIX_CONFIG: "experimental-features = nix-command flakes"
  COMMAND_WRAPPER: "nix develop .#ci --command bash -c"

test:
  stage: test
  script:
    - ${COMMAND_WRAPPER} "dotnet test --collect:'XPlat Code Coverage' --logger:junit --results-directory TestResults"
  artifacts:
    when: always
    paths:
      - TestResults/TestResults.xml
      - TestResults/*/coverage.cobertura.xml
    reports:
      junit: TestResults/TestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: TestResults/*/coverage.cobertura.xml

package:
  stage: package
  script:
    - ${COMMAND_WRAPPER} "dotnet pack --configuration Release --output nupkg -p:AssemblyVersion=${CI_COMMIT_TAG} -p:Version=${CI_COMMIT_TAG}"
  artifacts:
    paths:
      - nupkg
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/

publish:
  stage: publish
  script:
    - ${COMMAND_WRAPPER} "dotnet nuget push nupkg/ --api-key ${NUGET_API_KEY} --source 'https://api.nuget.org/v3/index.json'"
  rules:
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/